### ISSUE TITLE
Please go to https://accounts.somfy.com/... and authorize access

### ISSUE THREAD

**Issue by PythonPhilipp** [tetienne/somfy-open-api#102]
@tetienne , thank your for this great idea to provide the Somfy API in Python 3.

- I followed your instructions from README.md and got developer credentials from https://developer.somfy.com

- Afterwards I created an venv

`python -m venv env`

- Inside this venv I installed pymfy via pip

`pip install pymfy`

- I create a script on the basis of your example usage to print all covers position

- By running this script with

`python test.script`

I got following response:

Please go to https://accounts.somfy.com/oauth/oauth/v2/auth?response_type=code&client_id=my-secret-id&redirect_uri=https%3A%2F%2Fwww.google.com%2F&state=nZsqHxtz5YImQJv3ME2UE8I3v21d8R and authorize access.

Is this error familiar to you? Might you help me to solve this problem?

**Comment by tetienne** [comment]
Hi @PythonPhilipp I guess you didn’t read fully the exemple within the README.
```
api = SomfyApi(client_id, secret, redir_url)
authorization_url, _ = api.get_authorization_url()
print("Please go to {} and authorize access.".format(authorization_url))
authorization_response = input("Enter the full callback URL")
code = parse_qs(urlparse(authorization_response).query)["code"][0]
api.request_token(code=code)
```
The response you got is normal, it’s what you copy/paste (line 3 above). You have to follow the link and authorize the access and copy/paste the url you see in your browser once did.

**Comment by PythonPhilipp** [comment]
Hi @tetienne I really feel sorry for asking this beginner question, but I don't understand the workflow respectively the concept behind it.

- It is non-transparent for me, why I have to enter a callback URL at the Somfy Website and, furthermore, why I have to copy/paste resultts into the source code.

- Is it possible to use somfy-open-api from Python only?

**Comment by tetienne** [comment]
The Somfy official API authentification is performed by OAuth2. You can have more details [here](https://developer.somfy.com/apis-docs). OAuth2 is mainly used for the 3rd party application and ease the integration. For instance, this library is used by [Home Assistant](https://www.home-assistant.io/integrations/somfy/).

Whereas the [Tahoma API](https://github.com/iMicknl/python-tahoma-api/) (you already seen) uses a classic username/password authentification.
