### ISSUE TITLE
Rate limit quota violation

### ISSUE THREAD

**Issue by totothekiller** [tetienne/somfy-open-api#109]
Hello @tetienne  !

Since two or tree days I have lost all my Somfy covers  in my Home Assistant installation ... During HA initialization the call of _get_devices_ return no devices.

I have found that Somfy return a 500 response in [GetDevicesBySiteId](https://github.com/tetienne/somfy-open-api/blob/master/pymfy/api/somfy_api.py#L67) :

```json
{
   "fault":{
      "detail":{
         "errorcode":"policies.ratelimit.QuotaViolation"
      },
      "faultstring":"Rate limit quota violation. Quota limit exceeded."
   }
}
```

I have 3 sites available and I thinks that the loop on _site_id_ trigger the rate limitation. 

With a breakpoint in [L66](https://github.com/tetienne/somfy-open-api/blob/master/pymfy/api/somfy_api.py#L66) and manually wait a little I have all my covers back !

Ideas : 
- Handle this 500 Error code in [L73](https://github.com/tetienne/somfy-open-api/blob/master/pymfy/api/somfy_api.py#L73)
- add a wait before calling Somfy API
- filter on _site_id_ in HA side 

What do you think ?

Thanks for your help

**Comment by tetienne** [comment]
Hi, thx for this detailed issue. It's interesting to see Somfy can return error messages with their API.

I will contact them about this.

Do you reproduce each time when you call get_devices?

**Comment by totothekiller** [comment]
Yes every time I call _get_devices_ in my test python project I get no device returned. (Same in HA I guess)

**Comment by tetienne** [comment]
I’ve contacted their support 🤞 I hope I can avoid the sleep when iterating.

**Comment by tetienne** [comment]
I got this issue too now. But I have only one site.

**Comment by tetienne** [comment]
See https://github.com/home-assistant/core/issues/50815#issuecomment-851277301

**Comment by jirimissbach** [comment]
@tetienne, is this something you can (and plan) address in the integration?

Cheers!

**Comment by tetienne** [comment]
@jirimissbach I’ve adready an idea of fix indeed. I hope today (if Somfy stop returning error 500 when I test it...) It will be done directly in HA, within  this lib I will just document the fact the poll interval for calling /site must be greater than 1 minutes.

**Comment by jirimissbach** [comment]
Perfect, thanks!

Btw the API is working for me occasionally  (in between the errors)

**Comment by tetienne** [comment]
As a follow up of this issue, I created this one: https://github.com/tetienne/somfy-open-api/issues/145

**Comment by tetienne** [comment]
Hi, please see https://github.com/tetienne/somfy-open-api/issues/205
