### ISSUE TITLE
authorization fails with an error

### ISSUE THREAD

**Issue by catay** [tetienne/somfy-open-api#135]
Hi, 

Quick question to check if I'm missing something. 

I have an account on https://developer.somfy.com/ and my blinds are linked to this account.
When I use  the site API by using the try out option on the portal ( https://developer.somfy.com/somfy-open-api/apis/get/site), 
it all works and I get the correct response back.

When I create my own app in the portal (shows up as approved)  and I use the client_id/secret and so on with somfy-open-api,  it doesn't work.  On authorizing with the same account,  I always get 'An error has occurred. Please try again. If the problem persists, please contact our technical support team.' 

Would this be a problem on the somfy portal or could it be something I'm missing ? 

It's also not clear how to contact the technical support team. I tried the contact form but  no response. 
Do you have a contact ?

Any help or pointers would be appreciated ! :)

Steven

**Comment by tetienne** [comment]
Hi, that's a common issue. You did the things right. From their support, apparently there is a delay when an application is created (synchronization). 

But myself, I had to create several applications to finally succeed...

To contact them you have to use the form you already found on the api site. And they don't answer everytime. Their is only one guy behind.

**Comment by catay** [comment]
Merci for the fast response !  Let me bug their support a bit more ! :)

**Comment by Aeosium** [comment]
Hello!

I am reopening the issue as I am facing the same exact problem. Tried several things, with different callback urls, through the pymfy package or the implementation in home-assistant, I generated a few apps and waited for a couple of days... Unfortunately all with no luck :( . 

I contacted the Somfy API contact form just in case but any ideas meanwhile or should we just wait?

Thanks for the amazing work!

**Comment by catay** [comment]
@Aeosium  so far I have no luck with this.  Tried to contact them multiple times but no response.
I'm thinking of raising it through their social media channels on twitter  ... maybe they give it then the necessary attention.

**Comment by Aeosium** [comment]
@catay @tetienne 
I just got a reply stating that there is an issue on their side for app creation, nothing to do on our side except to wait for them to deploy a fix.

**Comment by Excodibur** [comment]
@Aeosium, @catay, @tetienne Does the login with the Somfy auth server work for you at the moment? I still experience the same issue you describe, no matter how many apps I create, or what redirect URL I provide/configure.

**Comment by tomasroud** [comment]
Hi, same here. I created 5 apps, same problem. They do not callback. I wrote them and I'm waiting. Hope they have any time before Xmas

**Comment by YossiCohen** [comment]
anyone here solved the issue? @tomasroud @Excodibur

**Comment by Excodibur** [comment]
@YossiCohen To be honest I did not try it again, yet. Somfy support did not reply at all to my mail regarding the issue and honestly it feels like this whole service is not maintained professionally. I don't know anything about staffing on Somfy's side, but I did not want to invest any more time and nerves into what seems like a student-project to me.

**Comment by YossiCohen** [comment]
@Excodibur 
I bought the Connexoon from the guy that build my windows and since I had supplies issues it was delayed for some months. and now when it's here I can't use it as I wanted to (from code)...

That's sucks!
But I do have a plan B for that:
https://github.com/Nickduino/Pi-Somfy

The hardware is already at my house - only need to weld it...

**Comment by Excodibur** [comment]
@YossiCohen Good luck! 

I have only newer IO-devices at my home, but there are some alternatives for those, too: https://github.com/Excodibur/ioBroker.tahoma/blob/master/FAQ.md#i-want-to-steer-my-devices-locally-without-having-to-connect-to-online-somfy-servers

**Comment by YossiCohen** [comment]
@Excodibur Thanks for the info :)
Now I have plan C...

All I wanted is to write some code that open my windows to around 50% open...

**Comment by tetienne** [comment]
Hi, you can also have a try with https://github.com/iMicknl/python-overkiz-api I maintain too with 2 others guys. This API is far more powerful ad stable.

This is the lib behind the Overkiz integration within Home Assistant.
