### ISSUE TITLE
How to authenticate ?

### ISSUE THREAD

**Issue by donnib** [tetienne/somfy-open-api#14]
Hi @tetienne
I want to try the API to see what it outputs for the Somfy swithes i have but i am unsure what i need from the Somfy API page, on the API page i have ```Consumer Key```, ```Consumer Secret``` but you are asking for ```client_id``` , ```redir_url``` and ```secret``` . Alo regarding the callback URL i guess it's equal to ```redir_url```and do i have to have a webserver that is open to the public that the API can be accessed from it or ?

/donnib

**Comment by koomik** [comment]
Hi, i'm not @tetienne (but you have already seen it LOL)
to help you, this is what i'm using
   `client_id = Consumer Key`
   `secret = Consumer Secret`
If your setup is not public (like mine)
   `redir_url = Callback URL = http://<internal_ip_homeassistant>:<web_port>/auth/somfy/callback`

Arnaud

**Comment by tetienne** [comment]
Hi @donnib,
I've updated the readme file to be more clear. @koomik (glad to see you here ;)) gave you the right information. For the redirect url/callback, if it's just to play with this API, set what you want. But later, if you want to use your Somfy account within Home Assistant for instance you will have to set indeed the home assistant address.

**Comment by donnib** [comment]
@koomik @tetienne thank you, got it working.
