### ISSUE TITLE
FileNotFoundError /optional/cache/path

### ISSUE THREAD

**Issue by TroisSix** [tetienne/somfy-open-api#16]
Hello tetienne,

I had a success with the script to get all the devices :)

But I encounter an error with the script to display only the covers, and I don't understand what is missing with this error : 
```
  File "GetCovers.py", line 31, in <module>
    set_token(api.request_token(code=code))
  File "GetCovers.py", line 21, in set_token
    with open(cache_path, 'w') as cache:
FileNotFoundError: [Errno 2] No such file or directory: '/optional/cache/path'
```

Do you have an idea?

Thank you for your help.

**Comment by tetienne** [comment]
```python
cache_path = '/optional/cache/path'
api = SomfyApi(client_id, secret, redir_url, token=get_token(), token_updater=set_token)
if not os.path.isfile(cache_path):
    authorization_url, _ = api.get_authorization_url()
    print('Please go to {} and authorize access.'.format(authorization_url))
    authorization_response = input('Enter the full callback URL')
    code = parse_qs(urlparse(authorization_response).query)['code'][0]
    set_token(api.request_token(code=code))
```

Hi @TroisSix. You got this error because you didn't change the value of `cache_path`. It has to be a true path (e.g. /home/tetienne/somfy_token).
But if you don't care about cache (meaning, it's just a one shot try), you can simply do:

```python
import os
import json
from urllib.parse import urlparse, parse_qs

from pymfy.api.devices.roller_shutter import RollerShutter
from pymfy.api.somfy_api import SomfyApi
from pymfy.api.devices.category import Category

client_id = r'<CLIENT_ID>' # Consumer Key
redir_url = '<REDIR_URL>' # Callback URL (for testing, can be anything)
secret = r'<secret>' # Consumer Secret

api = SomfyApi(client_id, secret, redir_url)
authorization_url, _ = api.get_authorization_url()
print('Please go to {} and authorize access.'.format(authorization_url))
authorization_response = input('Enter the full callback URL')
code = parse_qs(urlparse(authorization_response).query)['code'][0]
set_token(api.request_token(code=code))
devices = api.get_devices(category=Category.ROLLER_SHUTTER)

covers = [RollerShutter(d, api) for d in devices]
for cover in covers:
    print("Cover {} has the following position: {}".format(cover.device.name, cover.get_position()))
```

**Comment by TroisSix** [comment]
So easy it was, indeed :)

I still had an error cause the script cannot create the file, I just added a "os.touch(cache_path)" just before the token is written in the file.

It works perfect now, excellent job tetienne ;)

Just a few last questions:
- will I have all the time to copy and paste the url in a browser? I would like to use it within scripts and the token can only be created with this action?
- for the callback url, I put something for the tests and it works, but what should it really be? I use Domoticz, I haven't a "HASS"?
- I will try to include your work to allow Domoticz to use it: open a shutter with a x %, refresh the level in Domoticz, ... But I have seen somewhere that we can only use the API 6 times in a hour, does that limitation still exists?

Thank you :)
