### ISSUE TITLE
Auth: An error has occurred

### ISSUE THREAD

**Issue by mackaaij** [tetienne/somfy-open-api#182]
I was trying to list my devices as I have three and Home Assistant only shows one. I cannot connect to the Somfy API via an app I listed myself though.

If I open the [URL] that this script outputs in "Please go to [URL] and authorize access", the following error appears:

An error has occurred 
Please try again. If the problem persists, please contact
our technical support team.

Any idea how I can connect the script to the Somfy API?

**Comment by fedenunez** [comment]
It is an error on Somfy API side, it was already reported at: https://github.com/tetienne/somfy-open-api/issues/135, look at this comment: https://github.com/tetienne/somfy-open-api/issues/135#issuecomment-853234844

**Comment by mackaaij** [comment]
Thanks @fedenunez I'll close this as a duplicate. #135 is already closed, it looks like Somfy is not responding nor fixing the issue :( Maybe creating several apps and waiting for a while works.

**Comment by fedenunez** [comment]
> Thanks @fedenunez I'll close this as a duplicate. #135 is already closed, it looks like Somfy is not responding nor fixing the issue :( Maybe creating several apps and waiting for a while works.

We created around 10 apps, first one was back in April, still waiting... :(
