### ISSUE TITLE
Refactor lib to allow plugging in own OAuth clients

### ISSUE THREAD

**Issue by balloob** [tetienne/somfy-open-api#19]
We're building a free account linking service for Home Assistant. It will allow users to link their third-party accounts via OAuth2 without having to sign up for developer accounts etc.

I've been looking at the different implementations in Home Assistant that could support that, and it seems like the Somfy integration, based on this lib, is a great candidate to be the first implementation.

With the account linking service the client ID and secret will be kept in a cloud service, and all requests for getting access tokens (all grant types) will be routed via it. Authenticated requests to the Somfy API to interact with devices will still be made directly from Home Assistant to Somfy.

But to be able to get it working, we would need to update the `SomfyApi` class to take an instance of a class that implements `get` and `post`. The `get_authorization_url` and `request_token` methods could become helpers.

Would you accept a PR for this lib that accomplishes this? Will also update the Home Assistant side.

btw, are you on the Home Assistant Discord? I couldn't find you.

**Comment by tetienne** [comment]
@balloob I'm really surprised to see you here! Sure you are welcome to open a PR here. However, I don't see how you can avoid the end-user to create a dev account. You plan to contact Somfy too? 
We can discuss on Discord. My pseudo is itea (sadly, we are not allowed to change our nickname on HASS server).

**Comment by jensihnow** [comment]
Looking so much forward to it!

**Comment by tetienne** [comment]
@llavorel-somfy it will be a good news for Somfy I guess :)
