### ISSUE TITLE
Can't run the example code

### ISSUE THREAD

**Issue by YossiCohen** [tetienne/somfy-open-api#199]
I am trying to initially run the example script without success.
I've created an app:
![image](https://user-images.githubusercontent.com/13462946/159385345-b63fd959-6c64-4f9f-8e3f-6939df1cc7b2.png)

and I've put the client ID and secret in the python code.
as for the redirect URL - I've deployed a mock server that only log the content of the requests it gets.

When I run the Python code I get a URL but when I click it I get this error message:
![image](https://user-images.githubusercontent.com/13462946/159385636-a6293dd0-b228-4860-8ac4-e4ac78c8c64d.png)

What am I doing wrong?

**Comment by tetienne** [comment]
Hi, 

You are not doing something wrong. The issue is just on Somfy Server side. You are not the 1st one to report this. Plus Somfy does not maintain at all this service. I suggest you to look at https://github.com/iMicknl/python-overkiz-api instead.
