### ISSUE TITLE
error.invalid.grant

### ISSUE THREAD

**Issue by no1butme** [tetienne/somfy-open-api#202]
systematic error with pymfy 0.11.0 ; requests_oauthlib 1.3.1 ; Python 3.8.x ;
the same code used to work in 2019 with pymfy 0.5.x . I have the same error with the sample code in the home page for this project.

**Comment by tetienne** [comment]
Hi, 

I cannot help you on this. That’s probably again a new issue on their server. Meanwhile, please see https://github.com/tetienne/somfy-open-api/issues/205
