### ISSUE TITLE
503 Server Error: Service Unavailable

### ISSUE THREAD

**Issue by TroisSix** [tetienne/somfy-open-api#27]
Hi tetienne,
I replaced my sd card on my raspberry by a new one, and I backuped the old one to restore it on the new one.
I had to refresh the token, and I have an issue.
- I got the url to authorise : done
- I copy/paste the url in the console
- i get a fresh token (I think it's good?)
but I get the error : 
`Traceback (most recent call last):
  File "getCovers_20191105_2.py", line 33, in <module>
    devices = api.get_devices(category=Category.ROLLER_SHUTTER)
  File "/usr/local/lib/python3.7/dist-packages/pymfy/api/somfy_api.py", line 61, in get_devices
    site_ids = [s.id for s in self.get_sites()] if site_id is None else [site_id]
  File "/usr/local/lib/python3.7/dist-packages/pymfy/api/somfy_api.py", line 43, in get_sites
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.somfy.                      com/api/v1/site
`

PS: I simply use the script "Print all covers name" with my credentials.

What am i doing wrong?
Could you help me please?
Thank you ;)

**Comment by tetienne** [comment]
Hi, you are not doing anything wrong. Their is currently an issue on the Somfy servers. Sadly, we can just wait they solve this.

**Comment by TroisSix** [comment]
Pfff sont relous Somfy...
Are you able to inform us once you have some news? It's not the first time their api bugs :(
Thx.

**Comment by tetienne** [comment]
Usually is a matter of days, so it should be pretty soon.
