### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by gieljnssns** [tetienne/somfy-open-api#3]
Do you have plans integrating this in HA?

**Comment by tetienne** [comment]
That's the purpose behind this repo ;)

**Comment by gieljnssns** [comment]
Do you have have a timeline?
Because, I've installed my first screens and I wan't to integrate then in HA, so maybe is the best I wait until this new api is integrated...  (breaking changes?)

**Comment by tetienne** [comment]
Next week, I will probably have a try. Looking at the HA, it seems easy. But when you look some existing components, it's not so obvious.
Nevertheless, don't expect it public before the end of the year. Currently, only two kinds of devices are supported. So probably the architecture will evolve when I will discover new devices like thermostat for instance. I want this client to be stable.

**Comment by tetienne** [comment]
By the way @gieljnssns, can you check if the API returns well your screen?
Meanwhile, you can use the Tahoma component.

**Comment by gieljnssns** [comment]
I can not install this in a raspbian stretch virtual box...
could not find a version that satisfies the requirement pymfy (from versions:)
no matching distribution found for pymfy

**Comment by tetienne** [comment]
This project require python >=3.4 it 's why you got this issue.
Sorry for the delay, I didn't receive any notification.
