### ISSUE TITLE
Temperature parameter types in thermostat api

### ISSUE THREAD

**Issue by vlebourl** [tetienne/somfy-open-api#31]
Why limit the type temperature parameters to int? somfy's app accepts .5°C increments, and inputing float values seem to be cast correctly. But having float type parameters for temperature would seem more correct to me.

**Comment by tetienne** [comment]
According to the capabilities returned by Somfy, the temperature must be an integer: https://github.com/tetienne/somfy-open-api/blob/master/tests/hvac.json#L106 
So the real device allows float/double value?

**Comment by vlebourl** [comment]
Fair enough.

**Comment by tetienne** [comment]
@vlebourl What happened if you try to send float value?

**Comment by vlebourl** [comment]
it works as expected and sets the temperature to the given value with a 10-2 precision.

**Comment by tetienne** [comment]
OK, perhaps we can ask Somfy to update their capabilities.
