### ISSUE TITLE
Shutter movements

### ISSUE THREAD

**Issue by alan-maneg** [tetienne/somfy-open-api#39]
Hello tetienne,
thanks for this API.
I can get the status of my shutters but I don't understand how to move them.
I'm a novice ... and I don't understand everything in the Somfy documentation ...
thank you

**Comment by tetienne** [comment]
Hi, if you cannot use my library, it's probably some documentation are missing. I have to think about it. 
I guess you have run the example of the README? If yes, you did the most difficult part. 
The roller shutter class is defined here: https://github.com/tetienne/somfy-open-api/blob/master/pymfy/api/devices/roller_shutter.py

So if you want to move them, you can do for instance `cover.set_position(50)`.

**Comment by alan-maneg** [comment]
I was looking for a lot more complicated.
thank you so much

**Comment by alan-maneg** [comment]
Hello,
just a second problem:
I want to close my shutters in two steps: a small descent (25%) ; wait some time (1min) ; and then go down completely if I have not raised the shutters in the meantime.

I use the function `set_position(25)`
I wait 1 min `time.sleep(60)`
and I check the position of the panes with a `get_position()`
but the `get_position()` function is sometimes not up to date, is it possible to refresh the values?
Thank you again
Alan.

**Comment by tetienne** [comment]
Can you please share your full code?

**Comment by alan-maneg** [comment]
1. aa

**Comment by alan-maneg** [comment]
Hello,

[github.txt](https://github.com/tetienne/somfy-open-api/files/4239077/github.txt)
(Line45)
thank you

**Comment by tetienne** [comment]
@alan-maneg Sorry for the delay. I miss your comment.
So about your issue, it's a known one on Somfy side. The API server does not refresh automatically the state of the devices state. So it's why sometimes, you will see an out of sync between the API and your devices. You have to open the Tahoma website or application to refresh the state.
