### ISSUE TITLE
Somfy's expired certificate

### ISSUE THREAD

**Issue by tubededentifrice** [tetienne/somfy-open-api#40]
It appears Somfy's certificate expired today: https://api.somfy.com/api/v1/site
Dependent projects (I'm thinking about the Home Assistant integration) doesn't work anymore. France is under lock down and we can't be sure when the certificate will be updated. Also this situation could occur again in the future and/or be have certain use case.

Until then, maybe we could add a parameter to SomfyApi's constructor at https://github.com/tetienne/somfy-open-api/blob/master/pymfy/api/somfy_api.py so that requests are done without certificate verification?

**Comment by tubededentifrice** [comment]
NB: I contacted Somfy about this issue

**Comment by tetienne** [comment]
Hi, thank you for you suggestion. 

I will contact Somfy using their forum and their support service. Usually they answered me pretty fast.

I hope their own system warned them about this issue.

If no news Monday night, I will update the code to ignore the certificate error, which is imo not really good for security.

**Comment by joemadd3n** [comment]
Hoping this issue can be resolved soon, thank you for following up on this.

**Comment by thijsdejong** [comment]
@tetienne Issue has been fixed by Somfy 👍

**Comment by tetienne** [comment]
![image](https://user-images.githubusercontent.com/8216238/77409407-8078d000-6db9-11ea-9ddd-89aedc65b072.png)

Indeed, glad to see they are still working.
