### ISSUE TITLE
The redirect URI provided does not match registered URI(s).

### ISSUE THREAD

**Issue by jean1706** [tetienne/somfy-open-api#47]
Bonjour,
souhaitant utiliser l'API Somfy avec python, j'ai créé un compte développeur et installé somfy-open-api. Je teste avec votre script en ligne de commande, on me demande de valider et je suis redirigé vers une page qui me retourne en json : The redirect URI provided does not match registered URI(s).
En redirect URL, j'ai mis une adresse sur mon serveur en https (avec un certificat valide). C'est la même url que sur mon compte développeur somfy. Cette adresse doit-elle avoir une structure particulière ou bien effectuer un traitement ?
En vous remerciant,
Jean

**Comment by benito-domo** [comment]
Salut,
L'adresse que tu as dû mettre dans ton app Somfy (Callback URL) et dans le script de test (redir_url) doivent être identiques.
Peu importe si c'est une adresse valide ou non si tu veux juste faire le test, l'important c'est l'adresse que ton navigateur essaiera d'ouvrir qu'il faut ensuite copier.
Bonne chance :) !

**Comment by tetienne** [comment]
@jean1706 Cette erreur est vraiment pénible. Je l'ai rencontré de multiples fois également. Il semble que cela soit un soucis de synchro du côté de Somfy. Parfois attendre quelques heures peut suffire pour résoudre le soucis. Il n'y a pas de format requis pour l'URL. Comme le dit @benito-domo, même une URL ne pointant sur rien fonctionne.
Si le soucis continue encore, créez une autre application. Si cela échoue encore, contactez leur support.

**Comment by jean1706** [comment]
Merci beaucoup pour vos réponses.
J'ai essayé avec une nouvelle app mais ça bloque maintenant avant même que j'arrive sur la page d'autorisation... J'ai contacté le support voir s'il peuvent m'éclairer. Merci encore.
