### ISSUE TITLE
API down? Or something broken?

### ISSUE THREAD

**Issue by tubededentifrice** [tetienne/somfy-open-api#50]
For a couple days the integration seems to be broken (without anything in Home Assistant logs).
I tested it in Jupyter to rule out Home Assistant fault, turns out nothing is returned:

```
devices = api.get_devices(category=Category.ROLLER_SHUTTER)
covers = [RollerShutter(d, api) for d in devices]

print(devices)
print(covers)
```

```
[]
[]
```

I can still control my covers from the Somfy website though.
Am I the only one experiencing this?

**Comment by joemadd3n** [comment]
@tubededentifrice I am facing the same issues, looks like an issue with API. I've emailed Somfy but not sure how much success I'm going to have with that!

**Comment by joemadd3n** [comment]
@tubededentifrice is it easy to test using Jupyter? I haven't tried that.

**Comment by tubededentifrice** [comment]
Their API is really crappy, I can't count the number of times it has been down so far (but at least it returned errors, so we could know they were down), when their certificates isn't expired...

**Comment by joemadd3n** [comment]
> Their API is really crappy, I can't count the number of times it has been down so far (but at least it returned errors, so we could know they were down), when their certificates isn't expired...

haha! I was just going to say, wonder if their certificate is valid!

**Comment by tubededentifrice** [comment]
> @tubededentifrice is it easy to test using Jupyter? I haven't tried that.

Yep, just copy the "example usage" code from https://pypi.org/project/pymfy/

**Comment by tetienne** [comment]
What's the advantage to test using Jupyter vs vanilla Python?
An other way to be sure the issue come from their side, is to go on developer.somfy.com and use their sandbox.

**Comment by tubededentifrice** [comment]
> What's the advantage to test using Jupyter vs vanilla Python?
That's just a bit easier to use, no really any other advantage, and pretty much no real advantage in this case.

> An other way to be sure the issue come from their side, is to go on developer.somfy.com and use their sandbox.
Thanks, I didn't know about this.
`GetAllUserSite` (`/site`) returns `[]` ; since you need a `siteId` to get the devices, the journey ends very quickly...

**Comment by joemadd3n** [comment]
@tetienne 
Where are you seeing this? I can't find any sandbox?

`GetAllUserSite (/site) returns [] ; since you need a siteId to get the devices, the journey ends very quickly...`

**Comment by joemadd3n** [comment]
@tetienne API is now responding and returning data.

**Comment by tetienne** [comment]
Great. I close this issue.
