### ISSUE TITLE
Visualization of all equipment

### ISSUE THREAD

**Issue by thanaus** [tetienne/somfy-open-api#51]
Hello,

It is not really a bug but rather a request for help.
I do tests with the API directly (Somfy site) and I do not see all of my equipment (only a dozen out of thirty equipment).

How can we be sure that all the equipment is properly associated with the site ID ?

For information, I can see them from the Tahoma site :
https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/

**Comment by tetienne** [comment]
Currently only few devices are supported by the official api (not used by Tahoma link website). If you don't see them their is nothing we can do. You can contact their support to add your voice.
