### ISSUE TITLE
Control duration [feature  request]

### ISSUE THREAD

**Issue by grego1981** [tetienne/somfy-open-api#73]
Hi and I'm happy to report the thermostat works perfectly and without issues for the last month! 
I'd like to suggest to implement a mechanism to set the duration of the selected mode.  The issue is that when setting the mode after 12 hours or so it reverts to auto. If you have not the somfy app there are issues setting and keeping the preferred mode.

**Comment by tetienne** [comment]
Hi, I guess you are talking about the HA integration?

**Comment by grego1981** [comment]
Hi yes, for the HA integration

**Comment by tetienne** [comment]
OKi, can you please PM on the HA forum, with your use case?
