### ISSUE TITLE
Error fetching somfy device update data: No devices returned

### ISSUE THREAD

**Issue by BenFR23** [tetienne/somfy-open-api#77]
Hello Etienne,

since, not the last, but the previous update un december in home assistant I get this message.
All shutters switch to unavailable and come back few minutes later. 
(i've two Site ID, one is without device). 

Logger: homeassistant.components.somfy
Source: helpers/update_coordinator.py:166
Integration: Somfy (documentation, issues)
First occurred: 7 janvier 2021 à 21:13:57 (81 occurrences)
Last logged: 8:36:24

Error fetching somfy device update data: No devices returned

**Comment by tetienne** [comment]
@BenFR23 Hello! Thx for reporting this. See my comment [here](https://github.com/home-assistant/core/issues/44783#issuecomment-756618204).

**Comment by BenFR23** [comment]
I was pretty sure it was already reported... sry I didn't find it. Thanks !
