### ISSUE TITLE
Add ability to wait until command finishes

### ISSUE THREAD

**Issue by kecmen** [tetienne/somfy-open-api#88]
Hello,

first of all, thanks for developing this API for Somfy.

I'm not sure if this is a bug or feture request, but ss there a possibility how I can wait for some command to finishes? For example, if I want to set position and orientation for blinds, I'm doing it like this:
```
#...
blind = Blind(device, api)
blind.set_positon(85)
blind.orientation = 50
```
Lets suppose the blinds are fully down and closed. Then the code starts the position but immediatelly (well, half a second lets say) it sets the orientation which causes the position command to interrupt. The result is the blinds change the position slightly and then sets the orientation. Is there a way how I can wait until first command finishes (in this example set_position) and then run the other one?

Thanks

**Comment by tetienne** [comment]
Hi, what you asked totally make sense. Currently, Somfy returns an execution id for each command sent. But... That's all. We cannot do anything with it. You cannot also poll regularly the state as this one is not refreshed immediately. 

The only solution I can imagine is to use and ugly sleep of 10s for instance.

**Comment by kecmen** [comment]
Well I have time.sleep, just thought there might be better way. Sorry to hear they doesn't support this. Maybe in the future :)
Thanks
